name: Go

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Compile binary
      run: go build -v .
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: ["build-binary"]
    permissions:
      packages: write
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:0.0-${{ github.sha }},ghcr.io/${{ github.repository }}:latest
